### PR TITLE
Add install prompt to reinstall command when not installed

### PR DESCRIPTION
**Pull request by crumbtoo**
Added a prompt to install instead of dying when `betterdiscordctl reinstall` fails.

- - -
This change is [Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/145)

### CODE REVIEW

**Review by ObserverOfTime — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/145)* status: all files reviewed, 2 unresolved discussions (waiting on @crumbtoo)

___
*[`betterdiscordctl` line 345 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pB4LBColUKx6xPgZK:-N9pB4LBColUKx6xPgZL:undefined) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L345)):*
> ```
> 
>   if [[ "$ans" = "Y" || "$ans" = 'y' ]]; then
>     bdc_install
> ```





_Suggestion:_
```

  read -rp 'ERROR: Not installed. Install now? [y/N] '

  if [[ ${REPLY,} == y ]]; then
    bdc_install
```
___
*[`betterdiscordctl` line 348 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pAyo317yYxtSUpt3I:-N9pAyo317yYxtSUpt3J:undefined) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L348)):*
> ```
>     exit
>   else
>     exit
> ```





_Suggestion:_
```
   exit 1
```

**Review by bb010g — CHANGES_REQUESTED** [review]
This should occur only when the switch `--interactive` is passed; the current non-interactive default should be maintained. `--interactive` unfortunately can't use `-i` for its short form, as that's in use by the `--d-install` keyed option. `-I` might be second best, but I'm open to other labels.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-:-N9pQloaCzuzqgxikI9O:b-rg4apw)* status: all files reviewed, 10 unresolved discussions (waiting on @crumbtoo)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9p_l7k-wMrdybUmP39):*
First line of commit message is overly long. Please keep it to 50 characters or less. (See "Discussion" in [git-commit(1)](https://git-scm.com/docs/git-commit).)



_Code quote:_
```
Add install prompt to reinstall command when not installed
```
___
*[`betterdiscordctl` line 341 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pYow79iNs6yWWxl5g:-N9pLMRSBT7-ak9qax81:b8i1gk6) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L341)):*
> ```
> 
> bdc_install_prompt() {
>   echo -n "ERROR: Not installed. Install now? [Y/n] "
> ```

Warnings and errors should still be sent to standard error. Interactive output should be sent to standard output. The user shouldn't be lost if standard error is redirected somewhere they're not monitoring.



_Suggestion:_
```
  >&2 printf '%s\n' 'ERROR: Not installed.'
  printf '%s\n' 'BetterDiscord is not installed. Install now? [Y/n] ' 
```
___
*[`betterdiscordctl` line 341 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pYwFLCDYaW4x5p3Q6:-N9pYwFLCDYaW4x5p3Q7:b-9dhydl) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L341)):*
> ```
> 
> bdc_install_prompt() {
>   echo -n "ERROR: Not installed. Install now? [Y/n] "
> ```

If we can recover, it's not an error.



_Suggestion:_
```
  printf '%s\n' 'WARN: Not installed. Install now? [Y/n] '
```
___
*[`betterdiscordctl` line 341 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pZ0Dr90__62AwSqsO:-N9pZ0Dr90__62AwSqsP:b58xnmn) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L341)):*
> ```
> 
> bdc_install_prompt() {
>   echo -n "ERROR: Not installed. Install now? [Y/n] "
> ```

Behavior should be non-destructive by default.



_Suggestion:_
```
  printf '%s\n' 'ERROR: Not installed. Install now? [y/N] '
```
___
*[`betterdiscordctl` line 345 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pYSSR-8xVKHfbfp-L:-N9pYSSR-8xVKHfbfp-M:b-rfagei) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L345)):*
> ```
> 
>   if [[ "$ans" = "Y" || "$ans" = 'y' ]]; then
>     bdc_install
> ```

Rollup of local suggestions, and some extra changes. (Newline and `^D` should be dealt with properly. Prompt response parsing can fail, which requires reprompting. Convention is that we don't have to wait for newline when parsing a single character response.)



_Suggestion:_
```
  >&2 printf '%s\n' 'WARN: Not installed.'
  while :; do
    read -r -n 1 -p 'BetterDiscord is not installed. Install now? [y/N] '
    printf '\n'
    if [[ -z "$REPLY" || "$REPLY" == [Nn] ]]; then
      die 'ERROR: Not installed.'
    elif [[ "$REPLY" == [Yy] ]]; then
      break
    fi
    printf 'Unknown prompt response: %s\n' "$REPLY"
  done
  bdc_install
```
___
*[`betterdiscordctl` line 346 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pPI2g5PoPXaLdjA0P:-N9pPI2g5PoPXaLdjA0Q:b9iz1cw) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L346)):*
> ```
>   if [[ "$ans" = "Y" || "$ans" = 'y' ]]; then
>     bdc_install
>     exit
> ```

This shouldn't exit, but instead return like any other command function.
___
*[`betterdiscordctl` line 348 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pP5RBBuCpXW_IBLDw:-N9pP5RBBuCpXW_IBLDx:bwlha3e) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L348)):*
> ```
>     exit
>   else
>     exit
> ```

Maintain non-interactive error messages in interactive paths when they still work. Additionally, abnormally ending execution should almost always happen via `die`.



_Suggestion:_
```
    die 'ERROR: Not installed.'
```
___
*[`betterdiscordctl` line 353 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pPYJ54pB2Syrune9r:-N9pPYJ63MH6UUOP3Yc7:by87o3q) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L353)):*
> ```
> 
> bdc_reinstall() {
>   grep -Fq "$bd_asar_name" "$d_core/index.js" || bdc_install_prompt
> ```

If control flow diverges here, make it obvious.



_Suggestion:_
```
  if ! grep -Fq "$bd_asar_name" "$d_core/index.js";
    bdc_install_prompt
    return "$?"
  fi
```

**Review by bb010g — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/145)* status: all files reviewed, 10 unresolved discussions (waiting on @crumbtoo)

**Review by ObserverOfTime — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/145)* status: all files reviewed, 8 unresolved discussions (waiting on @bb010g and @crumbtoo)

___
*[`betterdiscordctl` line 345 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/145#-N9pYSSR-8xVKHfbfp-L:-N9plfMM-dJskMimSwXq:bl19v65) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/e271bce48ca30f8155a23f38255758638c6f2ada/betterdiscordctl#L345)):*
<details><summary><i>Previously, bb010g (bb010g) wrote…</i></summary><blockquote>

Rollup of local suggestions, and some extra changes. (Newline and `^D` should be dealt with properly. Prompt response parsing can fail, which requires reprompting. Convention is that we don't have to wait for newline when parsing a single character response.)
</blockquote></details>

Nitpicking:



_Code snippet:_
```
  >&2 printf 'WARN: Not installed.\n'
  while :; do
    read -r -n1 -p 'BetterDiscord is not installed. Install now? [y/N] '
    if [[ -z $REPLY || $REPLY == [Nn] ]]; then
      die '\nERROR: Not installed.'
    elif [[ $REPLY == [Yy] ]]; then
      break
    fi
    printf '\nUnknown prompt response: %s\n' "$REPLY"
  done
  bdc_install
```

**Pull request closed without merging**
