### PR TITLE
Some useful additions and more

### PR DESCRIPTION
**Pull request by ObserverOfTime**
Additions:
- Version info
- Self-update functionality *(you will obviously need to change the GitHub link to your own)*
- Usage instructions
- Snap support to remedy issue #1 

More: 
- Edited the script's formatting (this is just me nitpicking but ¯\\_(ツ)\_/¯)
- Double verbosity can be set with `-vv` instead of `-v -v`
- Uninstall uses `rm -f` instead of `rm`
- Removed unnecessary checks on `mkdir -p` and `touch`
- Improved errors by reminding the user to use `--help`

---
This change is [Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/2)

### CODE REVIEW

**Comment by bb010g** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 15 unresolved discussions.

---

*[betterdiscordctl, line 24 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56Rsa1NqarQbqRmfTW:-L56Rsa1NqarQbqRmfTX:byketa) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L24)):*
> ```
> xdg_config="${XDG_CONFIG_DIR:-$HOME/.config}"
> data="${XDG_DATA_HOME:-$HOME/.local/share}/betterdiscordctl"
> version=1.1.0
> ```

Constants like `version` and `github_url` should be listed in their own section (before options) and have SCREAMING_SNAKE_CASE.

---

*[betterdiscordctl, line 25 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56Rhk_tqiOv-r6YNwU:-L56Rhk_tqiOv-r6YNwV:b12dc3y) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L25)):*
> ```
> data="${XDG_DATA_HOME:-$HOME/.local/share}/betterdiscordctl"
> version=1.1.0
> github_url='https://raw.githubusercontent.com/ObserverOfTime/betterdiscordctl/master/betterdiscordctl'
> ```

You'll need to fix this before merge.

---

*[betterdiscordctl, line 36 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56JbmxL1aE5XhgGtO_:-L56JbmybMWEnl6RV2mu:b-sfzsx0) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L36)):*
> ```
>   uninstall                      Uninstall BetterDiscord.
> 
> Options:
> ```

Options are listed first to maintain consistency with `git`, `systemctl`, `yarn`, and more common Unix commands that use commands for their CLI.

---

*[betterdiscordctl, line 39 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56K59fwa1frskEuMp9:-L56K59fwa1frskEuMpA:bq2xjtz) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L39)):*
> ```
>   -h, --help                     Display this help message and exit
>   -v, --verbose                  Increase verbosity
>   -s, --scan=DIRECTORY           Directory to scan for Discord installations (default '/opt')
> ```

The newlines should be kept, as they keep lines under 80 characters.

---

*[betterdiscordctl, line 49 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56R6_-cQaqdzC4d7Yq:-L56R6_-cQaqdzC4d7Yr:b-czsc0d) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L49)):*
> ```
>       --global-asar              Use the asar in PATH instead of a local installation
>       --snap                     Install to the snap installation of Discord
>   -V, --version                  Display version info and exit
> ```

Version should be the first option listed (and parsed).

---

*[betterdiscordctl, line 61 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56KRCx1vvEN_iC1Uyr:-L56KRCyuLgu03Q-WRfu:b836yv4) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L61)):*
> ```
> 
> die() {
>   printf '%s\n%s\n' "$1" 'Use "--help" for more information.' >&2
> ```

If a usage of `die` should tell users to check `--help`, that should be put in the argument. `die` should be usable for failing in cases where checking `--help` isn't useful.

---

*[betterdiscordctl, line 71 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56KhtMcmKzzuOJHybf:-L56KhtMcmKzzuOJHybg:bsg9q2t) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L71)):*
> ```
> # Offer to self-update
> github_version=$(curl -s "$github_url" | grep "version=" -m1 | cut -d '=' -f2)
> if [[ "$github_version" > "$version" ]]; then
> ```

This needs to be able to be turned off, and user-controllable. I'm not comfortable with calling `curl` every time someone looks at `--help` or `status`. An auto-update mechanism would need to store when the last update was (we already have a data dir for this), have a delay between checking for updates, and be able to be completely turned off for distribution methods that handle updating themselves. (They should be able to patch that on with a simple `sed` command.)

As such, it would probably be useful to offer a `self-update` command that runs the updater logic on demand. It should error out gracefully if autoupdating has been disabled. (See `rustup self update` for an example of this in practice.)

---

*[betterdiscordctl, line 87 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56LsINyniRNkkSxR0_:-L56LsINyniRNkkSxR0a:b1d56ve) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L87)):*
> ```
>           exit 1
>         fi
>         printf "betterdiscordctl has been updated and will now exit.\n" >&2
> ```

By running this automatically whenever an update is detected, this can break scripts that depend on `betterdiscordctl` to do what they tell it to do. We should offer an argument to temporarily disable updates (this can share the logic for the hard disable).

---

*[betterdiscordctl, line 113 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56I8Q_TWe3znbQT3Ic:-L56I8QbIBU9C4ztwmFS:b-srueve) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L113)):*
> ```
>       ((++verbosity))
>       ;;
>     -vv)
> ```

`-vv` being a special case is inconsistent, especially with how it sets to 2, making `-v -v -v` or `-vv -v` give a verbosity of 3 but `-v -vv` give a verbosity of 2. It's simpler to just say that you can't combine short options, and have everything actually work.

---

*[betterdiscordctl, line 199 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56RDF9B9KUCSY3m7TT:-L56RDF9B9KUCSY3m7TU:bd83d7) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L199)):*
> ```
>       ;;
>     -V|--version)
>       printf "betterdiscordctl "$version"\n" >&2
> ```

`printf 'betterdiscordctl %s\n' "$version" >&2`

---

*[betterdiscordctl, line 216 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56IZxwBtsCM6TJjsl3:-L56IZxwBtsCM6TJjsl4:bpznkkr) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L216)):*
> ```
> done
> 
> mkdir -p "$data" && touch "$data/bd_map"
> ```

The checks were intentional. You can remove the data dir check if you really like, but I want to avoid touching `bd_map` if I don't need to, as `touch` will change the last modified time.

---

*[betterdiscordctl, line 228 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56NJFZsJvcFzMXkkN6:-L56NJFZsJvcFzMXkkN7:bf95ogg) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L228)):*
> ```
>           verbose 2 "VV: Detected $discord" >&2
>           if [ "$snap" ]; then
>             tmp_config="$HOME/snap/discord${flavor,,}/current/.config/discord${flavor,,}"
> ```

We should retrieve the Discord application directory using `snap`. I don't have Snap on my system, but looking through the documentation, it looks like we could probably pull from either [`snap info`](https://docs.snapcraft.io/reference/snap-command#info) with the appropriate flavor's snap name, or from [`snap run --shell <snap>.<comand> <<< 'echo "$SNAP_USER_DATA"'`](https://docs.snapcraft.io/reference/env).

---

*[betterdiscordctl, line 299 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56MqSbKEWGssfxS_qe:-L56MqSbKEWGssfxS_qf:b-xkjf5p) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L299)):*
> ```
>   printf 'Core patched: %s\n' "$core_patched"
>   printf 'Linked core directory: %s\n' "$linked_dir"
>   printf 'Linked core repository: %s\n' "$linked_repo"
> ```

I'd prefer to keep this as one print command.

---

*[betterdiscordctl, line 373 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56MbsrNJVpKySycaLr:-L56MbsrNJVpKySycaLs:bc2zd9q) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L373)):*
> ```
>   # Clean up legacy cruft
>   if [ -d "$discord/resources/app" ]; then
>     rm -rf "$discord/resources/app"
> ```

Could you offer an argument for why `-f` should be used here? (I'd prefer to be careful.)

---

*[README.md, line 10 at r1](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L56IzBzH32B45TEZjVm:-L56IzC-2zVtQHL32mDh:b92tyyv) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/README.md#L10)):*
> ```Markdown
> ## Usage
> 
> Some simple instructions can be found [here](./USAGE.md).
> ```

Usage should just be a part of the README if we're including it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2)*

**Comment by ObserverOfTime** [comment]
> You'll need to fix this before merge.
I'm not sure what you mean by "this." The URL?

> it would probably be useful to offer a self-update command that runs the updater logic on demand.
I guess it could be called `upgrade` and have new flags to let the user choose which repo to update from (much like `-r` works for BD).

> Usage should just be a part of the README if we're including it.
Verbose usage instructions are usually not included in the README so as not to convolute it.

For the rest, I'll comply with your comments.

**Comment by bb010g** [comment]
This is looking much better now! Thanks for catching the inconsistencies that I left there. All that's left is figuring out how to properly do the README, and I think we're good.

---

Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[betterdiscordctl, line 71 at r1](https://beta.reviewable.io/reviews/bb010g/betterdiscordctl/2#-L56KhtMcmKzzuOJHybf:-L5Ap5Pd0W7s_HInRPbT:b-ldz3o) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L71)):*
<details><summary><i>Previously, bb010g (Brayden Banks) wrote…</i></summary><blockquote>

This needs to be able to be turned off, and user-controllable. I'm not comfortable with calling `curl` every time someone looks at `--help` or `status`. An auto-update mechanism would need to store when the last update was (we already have a data dir for this), have a delay between checking for updates, and be able to be completely turned off for distribution methods that handle updating themselves. (They should be able to patch that on with a simple `sed` command.)

As such, it would probably be useful to offer a `self-update` command that runs the updater logic on demand. It should error out gracefully if autoupdating has been disabled. (See `rustup self update` for an example of this in practice.)
</blockquote></details>

OK. Forgot that `upgrade` wasn't used, so that name fits better.

---

*[betterdiscordctl, line 87 at r1](https://beta.reviewable.io/reviews/bb010g/betterdiscordctl/2#-L56LsINyniRNkkSxR0_:-L5Ap4pp8yFWmmenAEQx:b-8e6gs9) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/betterdiscordctl#L87)):*
<details><summary><i>Previously, bb010g (Brayden Banks) wrote…</i></summary><blockquote>

By running this automatically whenever an update is detected, this can break scripts that depend on `betterdiscordctl` to do what they tell it to do. We should offer an argument to temporarily disable updates (this can share the logic for the hard disable).
</blockquote></details>

OK. Didn't have to scrap the autoupdate, but this works.

---

*[betterdiscordctl, line 363 at r2](https://beta.reviewable.io/reviews/bb010g/betterdiscordctl/2#-L5ApKxB8xOoZWgePKFA:-L5ApKxB8xOoZWgePKFB:b-a2g859) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/b9ac41cad76d49ae9c46587bf1438245415a2e09/betterdiscordctl#L363)):*
> ```
> }
> 
> bdc_upgrade() {
> ```

BTW, this should still have a way to be disabled by a packager, but it's not a big enough issue to hold this up. I can hit that after the merge pretty quickly.

---

*[README.md, line 10 at r1](https://beta.reviewable.io/reviews/bb010g/betterdiscordctl/2#-L56IzBzH32B45TEZjVm:-L5AptOJ2JjqC2g_qehM:bxr7eeh) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/36333164718aab1d6548dcf1176d8a58add2922a/README.md#L10)):*
> Verbose usage instructions are usually not included in the README so as not to convolute it.

If we can't properly put quality usage instructions in the README, the README needs fixing. USAGE is split into Requirements (with installation instructions), Installation (for a global install), and finally basic examples. We can either introduce a man-style **Examples** section, improve the README's **Dependencies** section, and add an **Installation** section going over how to do a basic global install or just use locally, or introduce a more toned-down **Usage** section that covers all of this in a bit more step-by-step way, with optional improvement of the rest of the README.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bb010g/betterdiscordctl/2#-:-L5ArmHS3Bd5sRDoQkOX:bw823rz)*

**Comment by bb010g** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[README.md, line 5 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BFFqyYTOYHtTtcB9e:-L5BFFqzAuQl5oGKhY8B:bdxep1b) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L5)):*
> ```Markdown
> A utility for managing BetterDiscord on Linux.
> 
> ## Table of Contents
> ```

A table of contents seems a bit overboard for this.

---

*[README.md, line 24 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BFN1C1urD58QoA-xJ:-L5BFN1C1urD58QoA-xK:biuayko) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L24)):*
> ```Markdown
> ### Node & npm
> 
> Install using your [package manager][node-packages]
> ```

How is this more clear than the previous paragraph? All this seems to add is more space between each line. All I think that's needed here is a link to Git's download page and probably `download them` for the link text for Node.

---

*[README.md, line 89 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BETCRDItEnaboyJUx:-L5BETCSYTeh3zs3VpCc:bhnsgfx) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L89)):*
> ```Markdown
> ### `--snap`
> 
> Needed for `betterdiscordctl` to find the modules directory if Discord was installed via snap. Furthermore, it automatically sets `-c` because symlinks don't work.
> ```

Snap should either be capitalized properly. Also, I think the second sentence might be better as "`-c` is set due to Snaps' restriction to only access their own directories." And actually, if that's the case, couldn't we just clone into the Snap's config directory? (That might be annoying to use with our current DB, but it's an idea.)

---

*[README.md, line 117 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BGzmK73b3amQsj5kK:-L5BGzmK73b3amQsj5kL:b-v36cai) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L117)):*
> ```Markdown
> Updates `betterdiscordctl` to the latest version available on GitHub.
> 
> ## Installation
> ```

This can go where **Dependencies** currently sits, and have Dependencies's content moved to the top of Manual. See [Sway's README](https://github.com/swaywm/sway/blob/7c3b0ffc324d913dd1c58b2497c9c36c74580ded/README.md#installation) for an example.

---

*[README.md, line 119 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BG_LQ5ru6ex27Lhwj:-L5BG_LQ5ru6ex27Lhwk:bado76y) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L119)):*
> ```Markdown
> ## Installation
> 
> ### Arch
> ```

I'd rename this subheader to "Packages" and the next to "Manual".

---

*[README.md, line 121 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BFmJqEMl79jMqTklz:-L5BFmJqEMl79jMqTkm-:bgvakui) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L121)):*
> ```Markdown
> ### Arch
> 
> You can install `betterdiscordctl` from [AUR][AUR-package].
> ```

*the AUR

---

*[README.md, line 132 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BFzMOqdXA-ibvsaNU:-L5BFzMOqdXA-ibvsaNV:bkptc3f) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L132)):*
> ```Markdown
> $ sudo mv betterdiscordctl /usr/local/bin
> ```
> > /usr/local/bin must be in your `PATH` for this to work.
> ```

Given how the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) talks about `/usr/local/bin` being the [normal place](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html) for non-standard installs, `/usr/local/bin` should almost always be in `$PATH` by default, and we don't need to mention it here.

---

*[README.md, line 142 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BHUSgXDzL5ZuLAKwY:-L5BHUSgXDzL5ZuLAKwZ:b-cpk6je) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L142)):*
> ```Markdown
> ## Examples
> 
> ### Status (Discord in `/usr/share/discord`)
> ```

Examples shouldn't have headers. Just use paragraphs.

---

*[README.md, line 163 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BHnafBFiHkKufkeJj:-L5BHnagLJUKFyNcHNmR:b-ixwu2u) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L163)):*
> ```Markdown
> 
> ```
> $ betterdiscordctl uninstall -s /snap/discord/current/usr/share --snap
> ```

Shouldn't you just be able to pass `--snap` and have this work?

---

*[README.md, line 166 at r3](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-L5BHrCPMiiWUlW3P8_4:-L5BHrCPMiiWUlW3P8_5:b-g83rgc) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L166)):*
> ```Markdown
> ```
> 
> ## Locations
> ```

Didn't think about this. It's a nice idea. Could you use less headers, though?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2)*

**Comment by bb010g** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 163 at r3](https://beta.reviewable.io/reviews/bb010g/betterdiscordctl/2#-L5BHnafBFiHkKufkeJj:-L5Bn6L5-rdk073Rllr9:b99haz0) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/3fe774b8639c97a1f176b6bd1cafba4020c9af17/README.md#L163)):*
> theoretically yes but it wouldn't hurt to be safe in case the user moved it

Isn't that why we query `snap` for where the user put it?

Actually, looking at the detection code again, we don't. It'd be simpler to have `--snap` skip the usual detection logic and just query `snap` for where the proper Discord flavor's directories are the whole way. If they pass `--snap` and don't have a Snap with Discord's default names, fail. (We can cross the bridge of Discord installations via Snap renamed to not start with `discord` when we come to it.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bb010g/betterdiscordctl/2)*

**Comment by bb010g** [comment]
:lgtm:

We'll probably want to see about not hardcoding as much for Flatpak and Snap in the future, but this all looks great for now.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bb010g/betterdiscordctl/2#-:-L5FWEv0m_41qaEYRqwv:b4cq69p)*

**Pull request merged**
