### PR TITLE
Add Discord Development support

### PR DESCRIPTION
**Pull request by wgyt**
This change is [Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/138)

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
See https://github.com/BetterDiscord/BetterDiscord/issues/520#issuecomment-952035103

**Comment by wgyt** [comment]
> See [BetterDiscord/BetterDiscord#520 (comment)](https://github.com/BetterDiscord/BetterDiscord/issues/520#issuecomment-952035103)

I know that BetterDiscord's app doesn't support it, but I was able to use my patched version of betterdiscordctl to install BetterDiscord into my Development client.

**Comment by ObserverOfTime** [comment]
Last I checked, you had to manually create the config folder for BD to work and I believe there were still issues even then.

**Comment by wgyt** [comment]
> Last I checked, you had to manually create the config folder and edit the settings file for BD to work. Also, as far as I remember, there were still some issues even if you did all that.

I've had no issues with the latest development client and BD, even when I deleted all of my config and settings.

**Review by ObserverOfTime — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/138)* status: all files reviewed, 4 unresolved discussions (waiting on @wgyt)

___
*[betterdiscordctl, line 14 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/138#-MwLSIcXCr9UM1lkiYVp:-MwLSIcXCr9UM1lkiYVq:b2l52aw) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/c14fd0af470911b08f1dee4181d5117ccb2bf85e/betterdiscordctl#L14)):*
> ```
> cmd=
> verbosity=0
> d_flavors=('' development canary ptb)
> ```

`development` should be last.
___
*[betterdiscordctl, line 54 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/138#-MwLSKGS0W622g5t56JB:-MwLSKGS0W622g5t56JC:b2nreh6) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/c14fd0af470911b08f1dee4181d5117ccb2bf85e/betterdiscordctl#L54)):*
> ```
>   -f, --d-flavors <d_flavors>   discover Discord installations with the
>                                 colon-separated list of suffixes <d_flavors>.
>                                 Defaults to ':development:canary:ptb'. Flavors must 
> ```

Same as above.
___
*[README.md, line 61 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/138#-MwLS0J32yeGe9_1Fy1S:-MwLS0J32yeGe9_1Fy1T:bbxiav3) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/c14fd0af470911b08f1dee4181d5117ccb2bf85e/README.md#L61)):*
> ```Markdown
>   Decreases the verbosity level, for progressively less debugging information.
> 
> * `-f`, `--d-flavors` `<d_flavors>` (default `:canary:ptb`)
> ```

Add `development` here.
___
*[README.md, line 170 at r1](https://reviewable.io/reviews/bb010g/betterdiscordctl/138#-MwLSEWFAnEKS_dX5Ztv:-MwLSEWGDvH8hlQkpXcu:bfs15pw) ([raw file](https://github.com/bb010g/betterdiscordctl/blob/c14fd0af470911b08f1dee4181d5117ccb2bf85e/README.md#L170)):*
> ```Markdown
>   Installs BetterDiscord to the Canary flavor.
>   
> * `betterdiscordctl -f development install`
> ```

Remove this section.

**Review by ObserverOfTime — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wgyt)

**Pull request merged**
