### PR TITLE
Major improvements

### PR DESCRIPTION
**Pull request by ObserverOfTime**
Many additions and improvements in this PR. Specifically:

- Implemented `reinstall` command. Necessary for Canary's frequent updates.
	- Created `bdc_kill` and `bd_loader` functions to reuse the code.
- Major improvements in scanning:
	- Removed unnecessary loop.
	- Made fully case insensitive by using `find`.
	- It now also works when scanning directly (e.g. `-s /opt/discord`) which people often tend to do.
- Improved `upgrade` to use the script's source path and updated semver checking.
- Improved `die` to allow passing more than 2 arguments. (Might be useful later.)
- Removed the check for the legacy `app` directory in `status` which confused people.
	- In its place, I implemented a check for whether `index.js` has been modified. Useful since Discord overwrites the modifications when it updates.
- Fixed module directory checking to use the latest Discord version.
- Fixed semver checking in `upgrade`. (Was missing an `else`).
- Improved verbosity in various places.
- Changed the BD variable injection in `mainScreen.js` to append to the `use strict` line for consistency with the Windows & Mac installers.
- Finally, added Fedora copr repo to the package list.

---
This change is [Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/11)

### CODE REVIEW

**Comment by bb010g** [comment]
Sorry, forgot about this. I'll review this later today so #12 can get resolved quickly.

**Comment by ObserverOfTime** [comment]
@bb010g Did you forget about it again? :thinking:

**Comment by ObserverOfTime** [comment]
@bb010g Hey, if you don't respond within a week, I will be forced to proceed under the assumption that you have abandoned this project.

**Comment by bb010g** [comment]
Sorry, been planning to get to this for a while, but I haven't had good time when remembering it. Feel free to PM me on Discord about this stuff in the future. LGTM save for the semver code, which I just took and rewrote to be purely expansions and builtins, and some array handling, which I cleaned up with the help of [shellcheck](https://github.com/koalaman/shellcheck) and Greg's Wiki ([Guide](http://mywiki.wooledge.org/BashGuide/Arrays), [FAQ entry](http://mywiki.wooledge.org/BashFAQ/005)).

**Comment by bb010g** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bb010g/betterdiscordctl/11)*

**Comment by bb010g** [comment]
I'll cut a 1.4.0 now.

**Pull request merged**
